CinemaTickets/src/CinemaTickets.Web/Models/BuyTicketViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CinemaTickets.Web.Models
{
    public class BuyTicketViewModel
    {
        [Required]
        public long MovieSessionId { get; set; }

        [DisplayName("Please, select seat for Buy")]
        [Required]
        public long SeatId { get; set; }
    }
}

CinemaTickets/src/CinemaTickets.Web/Controllers/CinemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CinemaTickets.Domain.Dtos.Cinema;
using CinemaTickets.Services.Application.ViewModels.Cinema;
using CinemaTickets.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CinemaTickets.Web.Controllers
{
    [Route("[controller]")]
    public class CinemaController : Controller
    {
        private IMapper _mapper;
        private ICinemaService _cinemaService;

        public CinemaController(IMapper mapper, ICinemaService cinemaService)
        {
            _mapper = mapper;
            _cinemaService = cinemaService;
        }

        [Route("/cinemas")]
        public IActionResult Index()
        {
            List<CinemaForListDto> source = _cinemaService.GetAllByCityId();

            List<CinemaForListViewModel> model = _mapper.Map<List<CinemaForListViewModel>>(source);

            return View(model);
        }
    }
}

CinemaTickets/src/CinemaTickets.Web/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CinemaTickets.Domain.Dtos.Genre;
using CinemaTickets.Domain.Dtos.Movie;
using CinemaTickets.Services.Application.ViewModels.Genre;
using CinemaTickets.Services.Application.ViewModels.Movie;
using CinemaTickets.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CinemaTickets.Web.Controllers
{
    [Route("[controller]")]
    public class GenreController : Controller
    {
        private IMapper _mapper;
        private IGenreService _genreService;
        private IMovieService _movieService;

        public GenreController(IMapper mapper, IGenreService genreService, IMovieService movieService)
        {
            _mapper = mapper;
            _genreService = genreService;
            _movieService = movieService;
        }

        [Route("/genres")]
        public IActionResult Index()
        {
            List<GenreBaseInfoDto> source = _genreService.GetAll();

            List<GenreForListOfGenresViewModel> model = _mapper.Map<List<GenreForListOfGenresViewModel>>(source);

            return View(model);
        }

        [Route("{id}")]
        public IActionResult Get(long id)
        {
            GenreBaseInfoDto source = _genreService.GetBaseInfoById(id);
            List<MovieInGenreDto> movieSource = _movieService.GetMoviesByGenre(id);

            GenreViewModel model = _mapper.Map<GenreViewModel>(source);
            model.Movies = _mapper.Map<List<MovieInGenreViewModel>>(movieSource);

            return View(model);
        }
    }
}

CinemaTickets/src/CinemaTickets.Web/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CinemaTickets.Domain.Dtos;
using CinemaTickets.Domain.Dtos.Actor;
using CinemaTickets.Domain.Dtos.Country;
using CinemaTickets.Domain.Dtos.Director;
using CinemaTickets.Domain.Dtos.Genre;
using CinemaTickets.Domain.Dtos.Language;
using CinemaTickets.Domain.Dtos.Movie;
using CinemaTickets.Domain.Dtos.Writer;
using CinemaTickets.Infrastructure.Data.Repositories.Interfaces;
using CinemaTickets.Services.Application.ViewModels;
using CinemaTickets.Services.Application.ViewModels.Actor;
using CinemaTickets.Services.Application.ViewModels.Country;
using CinemaTickets.Services.Application.ViewModels.Director;
using CinemaTickets.Services.Application.ViewModels.Genre;
using CinemaTickets.Services.Application.ViewModels.Language;
using CinemaTickets.Services.Application.ViewModels.Movie;
using CinemaTickets.Services.Interfaces;
using CinemaTickets.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CinemaTickets.Web.Controllers
{
    [Route("[controller]")]
    public class MovieController : Controller
    {
        private IMapper _mapper;
        private IMovieService _movieService;
        private IActorService _movieActorService;
        private ICountryService _countryService;
        private IDirectorService _directorService;
        private IGenreService _genreService;
        private ILanguageService _languageService;
        private IWriterService _writerService;
        private IOrderService _orderService;
        private ISeatService _seatService;

        public MovieController(IMapper mapper, 
            IMovieService movieService,
            IActorService actorService,
            ICountryService countryService,
            IDirectorService directorService,
            IGenreService genreService,
            ILanguageService languageService,
            IWriterService writerService, 
            IOrderService orderService, 
            ISeatService seatService)
        {
            _mapper = mapper;
            _movieService = movieService;

            _movieActorService = actorService;
            _countryService = countryService;
            _directorService = directorService;
            _genreService = genreService;
            _languageService = languageService;
            _writerService = writerService;
            _orderService = orderService;
            _seatService = seatService;
        }

        [Route("{id}")]
        [HttpGet]
        public IActionResult Display(long id)
        {
            MovieFullInfoDto source = _movieService.GetFullInfoOfMovieById(id);

            MovieInfoViewModel movie = _mapper.Map<MovieInfoViewModel>(source);

            return View(movie);
        }

        [Route("/movies")]
        [HttpGet]
        public IActionResult Index()
        {
            List<MovieInGenreDto> source = _movieService.GetMoviesByGenre();

            List<MovieInGenreViewModel> movies = _mapper.Map<List<MovieInGenreViewModel>>(source);

            return View(movies);
        }
        
        [Authorize(Roles = "admin, moderator")]
        [Route("/create")]
        [HttpGet]
        public IActionResult Create()
        {
            var movie = new MovieViewModel();

            SetViewDataVariables();

            return View("Edit", movie);
        }

        [Authorize(Roles = "admin, moderator")]
        [Route("edit/{id}")]
        [HttpGet]
        public IActionResult Edit(long id)
        {
            MovieDto source = _movieService.Get(id);

            MovieViewModel movie = _mapper.Map<MovieViewModel>(source);

            SetViewDataVariables();

            return View(movie);
        }

        [Authorize(Roles = "admin, moderator")]
        [Route("edit/{id?}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(MovieViewModel movie)
        {
            if (!ModelState.IsValid)
            {
                SetViewDataVariables();
                return View(movie);
            }

            var dto = _mapper.Map<MovieDto>(movie);
            _movieService.Update(dto);

            return RedirectToAction("Display", new {id = dto.Id});
        }

        [Authorize(Roles = "admin, moderator")]
        [Route("delete/{id}")]
        [HttpGet]
        public IActionResult Delete(long id)
        {
            _movieService.Delete(id);

            return RedirectToAction("Index");
        }

        [Route("buy-ticket")]
        [Authorize]
        [HttpGet]
        public IActionResult BuyTicket(long sessionId)
        {
            var model = new BuyTicketViewModel
            {
                MovieSessionId = sessionId
            };

            List<SeatDto> seats = _seatService.GetAllBy(sessionId);

            var sourceForSelectList = seats.Select(x => new
            {
                Value = x.Id,
                Label = $"[R = {x.RowNumber}, C = {x.ColumnNumber}] Type: {x.SeatType.ToLower()}"
            });

            ViewBag.Seats = new SelectList(sourceForSelectList, "Value", "Label");

            return PartialView("_BuyTicket", model);
        }

        [Route("buy-ticket")]
        [Authorize(Roles = "user")]
        [HttpPost]
        public IActionResult BuyTicket(BuyTicketViewModel model)
        {
            var movieId = _orderService.BuyTicketAndGetMovieId(User, new BuyTicketDto
            {
                MovieSessionId = model.MovieSessionId,
                SeatId = model.SeatId
            });

            return RedirectToAction("Display", new {id = movieId});
        }

        
        [HttpGet]
        [Route("tickets")]
        [Authorize]
        public IActionResult GetOrders()
        {
            List<OrderDto> orders = _orderService.GetAllBy(User);

            List<OrderViewModel> model = _mapper.Map<List<OrderDto>, List<OrderViewModel>>(orders);

            return View("Orders", model);
        }

        private void SetViewDataVariables()
        {
            List<ActorDto> actorsSource = _movieActorService.GetAll();
            List<CountryDto> countriesSource = _countryService.GetAll();
            List<DirectorDto> directorsSource = _directorService.GetAll();
            List<GenreSampleInfoDto> genresSource = _genreService.GetAllSample();
            List<LanguageDto> languagesSource = _languageService.GetAll();
            List<WriterDto> writersSource = _writerService.GetAll();

            ViewData["MovieActors"] = _mapper.Map<List<ActorViewModel>>(actorsSource);
            ViewData["MovieCountries"] = _mapper.Map<List<CountryViewModel>>(countriesSource);
            ViewData["MovieDirectors"] = _mapper.Map<List<DirectorViewModel>>(directorsSource);
            ViewData["MovieGenres"] = _mapper.Map<List<GenreSampleViewModel>>(genresSource);
            ViewData["MovieLanguages"] = _mapper.Map<List<LanguageViewModel>>(languagesSource);
            ViewData["MovieWriters"] = _mapper.Map<List<WriterViewModel>>(writersSource);
        }
    }
}

CinemaTickets/src/CinemaTickets.Web/Views/Movie/Display.cshtml
@model MovieInfoViewModel
    
@inject SignInManager<User> SignInManager
@inject RoleManager<Role> RoleManager

@{
    ViewBag.Title = $"Movie {Model.Name}";
}

<div class="row mt-2">
    <div class="col-lg-3 float-left d-block">
        <img class="w-100" src="~/images/movie-poster.jpg" alt="Movie poster"/>
        <dl>
            <dt data-toggle="modal" data-target="#trailer-modal">
                <a class="d-block rounded-link mt-2 text-center" href="#">
                    <span>
                        Trailer
                    </span>
                </a>
            </dt>
            
            @if (SignInManager.IsSignedIn(User) && (User.IsInRole("moderator") || User.IsInRole("admin")))
            {
                <dt id="edit-movie-button">
                    <a class="d-block rounded-link mt-2 text-center" asp-controller="Movie" asp-action="Edit" asp-route-id="@Model.Id">
                        <span>
                            Edit
                        </span>
                    </a>
                </dt>

                <dt id="delete-movie-button">
                    <a class="d-block rounded-link mt-2 text-center" asp-controller="Movie" asp-action="Delete" asp-route-id="@Model.Id">
                        <span>
                            Delete
                        </span>
                    </a>
                </dt>
            }
        </dl>
        <!-- Modal -->
        <div class="modal fade h-100" id="trailer-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg h-100" role="document">
                <div class="modal-content h-75">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Trailer: @Model.Name</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body h-75">
                        <iframe id="videowrapper" class="w-100 h-100" src="https://www.youtube.com/embed/4fVCKy69zUY?asdasd" frameborder="0" allowfullscreen></iframe>
                    </div>
                    <div class="modal-footer">
                        <button id="close-modal-btn" type="button" class="btn btn-danger" data-dismiss="modal"><span>Close</span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-7">
        <div class="row">
            <div class="col-lg-12 mb-3">
                <h2>@Model.Name</h2>
            </div>
        </div>
        <dl class="row">
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.AgeLimit):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayFor(m => m.AgeLimit)+
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.OriginalName):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayFor(m => m.OriginalName)
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.ReleaseDate):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Model.ReleaseDate.ToString("d", CultureInfo.CurrentUICulture)
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.Duration):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayFor(m => m.Duration) мин
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.Countries):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayList(Model.Countries)
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.Actors):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayList(Model.Actors)
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.Directors):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayList(Model.Directors)
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.Languages):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayList(Model.Languages)
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.Writers):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @Html.DisplayList(Model.Writers)
            </dd>
            <dt class="col-lg-2 float-left d-block mw-8rem">
                @Html.DisplayNameFor(m => m.Genres):
            </dt>
            <dd class="col-lg-10 float-left d-block">
                @{
                    int i;
                    for (i = 0; i < Model.Genres.Count - 1; i++)
                    {
                        <a asp-controller="Genre" asp-action="Get" asp-route-id="@Model.Genres[i].Id">@Model.Genres[i].Name</a>
                        <span>,</span>
                    }
                    <a asp-controller="Genre" asp-action="Get" asp-route-id="@Model.Genres[i].Id">@Model.Genres[i].Name</a>
                }
            </dd>
            <dd class="col-lg-12 my-3">
                @Html.DisplayFor(m => m.Description)
            </dd>
        </dl>
        <div class="row px-3">
            <div class="col-lg-12">
                <h5 class="row mb-3">
                    Reviews @Html.DisplayFor(m => m.Name)
                </h5>
                <div class="row mb-2">
                    <div>
                        <a id="like" class="mr-2">
                            <span class="pl-5 pr-3 py-2 rounded movie-like-dislike">
                                Like 
                                @Model.Likes
                            </span>
                        </a>
                        <a id="dislike" class="rounded ml-2">
                            <span class="pl-5 pr-3 py-2 rounded movie-like-dislike text-center">
                                Dislike
                                @Model.Dislikes
                            </span>
                        </a>
                    </div>
                    <div id="comment-numbers" class="m-auto">
                        <a>
                            <span class="pl-5 pr-3 py-2 text-center rounded">
                                Comments(@Model.Comments.Count)
                            </span>
                        </a>
                    </div>
                </div>
                <div class="row">
                    @{ await Html.RenderPartialAsync("_Comments", Model.Comments); }
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-2" style="overflow-y: auto;">
        @{ await Html.RenderPartialAsync("_MovieSessionsForMovie", Model.MovieSessions);}
    </div>
</div>

CinemaTickets/src/CinemaTickets.Web/Views/Movie/Edit.cshtml
@using System.Collections
@model MovieViewModel
@{
    ViewData["Title"] = $"Edit movie {Model.Name}";

    var movieActors = new MultiSelectList(ViewData["MovieActors"] as IEnumerable, "Id", "FullName");

    var movieCountries = new MultiSelectList(ViewData["MovieCountries"] as IEnumerable, "Id", "Name");


    var movieDirectors = new MultiSelectList(ViewData["MovieDirectors"] as IEnumerable, "Id", "FullName");

    var movieGenres = new MultiSelectList(ViewData["MovieGenres"] as IEnumerable, "Id", "Name");

    var movieLanguages = new MultiSelectList(ViewData["MovieLanguages"] as IEnumerable, "Id", "Name");

    var movieWriters = new MultiSelectList(ViewData["MovieWriters"] as IEnumerable, "Id", "FullName");
}

<div class="row">
    <form class="col-md-10 m-auto" asp-controller="Movie" asp-action="Edit" method="post" asp-antiforgery="true">
        <input type="hidden" asp-for="Id"/>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="Name"></label>
            <input type="text" class="form-control form-control-lg" asp-for="Name">
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="OriginalName"></label>
            <input type="text" class="form-control form-control-lg" asp-for="OriginalName">
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="Trailer"></label>
            <input type="url" class="form-control form-control-lg" asp-for="Trailer">
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="Duration"></label>
            <input type="number" class="form-control form-control-lg" asp-for="Duration">
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="ReleaseDate"></label>
            <input type="date" class="form-control form-control-lg" asp-for="ReleaseDate">
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="AgeLimit"></label>
            <input type="number" class="form-control form-control-lg" asp-for="AgeLimit">
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="ImdbRaiting"></label>
            <input type="text" class="form-control form-control-lg" asp-for="ImdbRaiting">
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="Description"></label>
            <textarea rows="4" class="form-control form-control-lg" asp-for="Description"></textarea>
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="MovieActors"></label>
            <select size="6" class="form-control form-control-lg" asp-for="MovieActors" asp-items="@movieActors"></select>
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="MovieDirectors"></label>
            <select size="6" class="form-control form-control-lg" asp-for="MovieDirectors" asp-items="@movieDirectors"></select>
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="MovieCountries"></label>
            <select size="6" class="form-control form-control-lg" asp-for="MovieCountries" asp-items="@movieCountries"></select>
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="MovieLanguages"></label>
            <select size="6" class="form-control form-control-lg" asp-for="MovieLanguages" asp-items="@movieLanguages"></select>
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="MovieWriters"></label>
            <select size="6" class="form-control form-control-lg" asp-for="MovieWriters" asp-items="@movieWriters"></select>
        </div>
        <div class="form-group">
            <label class="col-form-label-lg bold" asp-for="MovieGenres"></label>
            <select size="6" class="form-control form-control-lg" asp-for="MovieGenres" asp-items="@movieGenres"></select>
        </div>
        <input class="btn btn-success float-right" type="submit" value="Сохранить изменения"/>
    </form>
</div>

CinemaTickets/src/CinemaTickets.Web/Views/Movie/Index.cshtml
@model List<MovieInGenreViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="row mt-4">
    @foreach (MovieInGenreViewModel item in Model)
    {
        <a id="movie-in-genre-block" class="col-md-2 text-center mb-3" asp-controller="Movie" asp-action="Display" asp-route-id="@item.Id">
            <img class="img-fluid" src="~/images/movie-poster.jpg" alt="Movie poster" />
            <span class="d-block text-center">@item.Name</span>
        </a>
    }
</div>

CinemaTickets/src/CinemaTickets.Web/Views/Movie/Orders.cshtml
@model List<CinemaTickets.Services.Application.ViewModels.OrderViewModel>

@{
    ViewData["Title"] = "All bought tickets";
}

<div class="row p-5">
    @if (Model.Any())
    {
        <table class="col-md-12 table table-striped">
            <thead class="thead-inverse">
            <tr>
                <th>#</th>
                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().MovieTitle)</th>
                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().RowNumber)</th>
                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().ColumnNumber)</th>
                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().SeatType)</th>
                <th>@Html.DisplayNameFor(m => m.FirstOrDefault().Identifier)</th>
            </tr>
            </thead>
            <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <th scope="row">
                        @(i + 1)
                    </th>
                    <td>
                        <a asp-action="Display" asp-route-id="@Model[i].MovieId">@Model[i].MovieTitle</a>
                    </td>
                    <td>
                        @Model[i].RowNumber
                    </td>
                    <td>
                        @Model[i].ColumnNumber
                    </td>
                    <td>
                        @Model[i].SeatType.ToLowerInvariant()
                    </td>
                    <td>
                        @Model[i].Identifier
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    else
    {
        <h1>No tickets to display</h1>
    }
</div>

CinemaTickets/src/CinemaTickets.Web/Views/Movie/_BuyTicket.cshtml
@model BuyTicketViewModel

<div class="modal fade" id="buyTicketModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="BuyTicket" method="post">
                    @Html.HiddenFor(x => x.MovieSessionId)

                    <div class="form-group">
                        <label class="col-form-label bold" asp-for="SeatId"></label>
                        <select asp-for="SeatId" asp-items="ViewBag.Seats" class="col custom-select"></select>
                    </div>

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Buy</button>
                </form>
            </div>
        </div>
    </div>
</div>

CinemaTickets/src/CinemaTickets.Web/Views/Movie/_MovieSessionsForMovie.cshtml
@model List<MovieSessionForMovieViewModel>
    
@if (Model.Count == 0)
{
    <span id="no-movie-session">No sessions</span>
    <a asp-controller="Home" asp-action="Index">Pick other movie</a>
}
else
{
    <span id="movie-session-title" class="d-block mb-3">Sessions</span>

    var temp = from t in Model
        group t by new {t.Cinema.Id, t.Cinema.Name} into g
        select new
        {
            Cinema = g.Key,
            MovieSessions = g
        };

    foreach (var item in temp)
    {
        <a id="movie-session-cinema-name" class="d-block font-weight-bold mb-2" asp-controller="Cinema" asp-action="Get" asp-route-id="@item.Cinema.Id">
            @item.Cinema.Name.ToUpper(CultureInfo.CurrentUICulture)
        </a>
        foreach (MovieSessionForMovieViewModel session in item.MovieSessions)
        {
            <div id="movie-session" class="d-inline-block text-center mr-2 mb-2">
                <span id="movie-session-time" data-movie-session-id="@session.Id" class="d-block buy-ticket-modal-button" data-toggle="tooltip" title="from @session.MinPrice.ToString("F", CultureInfo.CurrentUICulture)">@session.Time.ToString("t", CultureInfo.CurrentUICulture)</span>
                <span id="movie-session-format">@session.Format.ToLower(CultureInfo.CurrentUICulture)</span>
            </div>
        }
        <hr />
    }

    <div id="modals">

    </div>
}

<script>
    $(function() {
        $(".buy-ticket-modal-button").click(function() {
            $.get(
                '@Url.Action("BuyTicket", "Movie")',
                {
                    sessionId: $(this).attr('data-movie-session-id')
                }
            ).done(function(data) {
                $("#modals").html($(data));
                $("#buyTicketModal").modal();
            });
        });
    });
</script>